create table books (key bigint generated by default as identity, author varchar(180) not null, launch_date date not null, price double not null, title varchar(250) not null, primary key (key));
create table permission (id bigint generated by default as identity, description varchar(255), primary key (id));
create table person (id bigint generated by default as identity, address varchar(100) not null, first_name varchar(80) not null, gender varchar(6) not null, last_name varchar(80) not null, primary key (id));
create table user_permission (id_user bigint not null, id_permission bigint not null);
create table users (id bigint generated by default as identity, account_non_expired boolean, account_non_locked boolean, credentials_non_expired boolean, enabled boolean, full_name varchar(255), password varchar(255), user_name varchar(255), primary key (id));
alter table users add constraint UK_k8d0f2n7n88w1a16yhua64onx unique (user_name);
alter table user_permission add constraint FKo47t1we6do84ku6rb9jcey2s9 foreign key (id_permission) references permission;
alter table user_permission add constraint FKprpp02ivhe66b5nrc0a3a4lk8 foreign key (id_user) references users;


INSERT INTO `person` (`id`, `address`, `first_name`, `gender`, `last_name`) VALUES
(1, 'Uberlândia - Minas Gerais - Brasil', 'Leandro', 'Male', 'Costa'),
(2, 'Uberlândia - Minas Gerais - Brasil', 'Gabriela', 'Female', 'Costa'),
(5, 'Patos de Minas - Minas Gerais - Brasil', 'Flávio', 'Male', 'Costa'),
(7, 'Uberlândia - Minas Gerais - Brasil', 'Fernanda', 'Female', 'Cardoso da Silva'),
(8, 'Patos de Minas - Minas Gerais - Brasil', 'Pedro', 'Male', 'Paulo'),
(9, 'Patos de Minas - Minas Gerais - Brasil', 'Marcos', 'Male', 'Paulo');




INSERT INTO `permission` (`description`) VALUES
('ADMIN'),
('MANAGER'),
('COMMON_USER');


insert into users (account_non_expired, account_non_locked, credentials_non_expired, enabled, full_name, password, user_name) values
(true, true, true, true, 'Caio Ferreira', '$2a$16$9qr2tv0HmXbHBsx.TZFjfux742wCZM32a8Wi6iBqwIqaizlHPuxHS', 'caiocf');

insert into users (account_non_expired, account_non_locked, credentials_non_expired, enabled, full_name, password, user_name) values
(true, true, true, true, 'Maria Ferreira', '$2a$16$h4yDQCYTy62R6xrtFDWONeMH3Lim4WQuU/aj8hxW.dJJoeyvtEkhK', 'maria');

-- caiocf / admin123
-- maria / admin456
/*INSERT INTO `users` (`user_name`, `full_name`, `password`, `account_non_expired`, `account_non_locked`, `credentials_non_expired`, `enabled`) VALUES
('caiocf', 'Caio Ferreira', '$2a$16$9qr2tv0HmXbHBsx.TZFjfux742wCZM32a8Wi6iBqwIqaizlHPuxHS', b'1', b'1', b'1', b'1'),
('maria', 'Maria Ferreira', '$2a$16$h4yDQCYTy62R6xrtFDWONeMH3Lim4WQuU/aj8hxW.dJJoeyvtEkhK', b'1', b'1', b'1', b'1');
*/


INSERT INTO `user_permission` (`id_user`, `id_permission`) VALUES
(1, 1),
(2, 1),
(1, 2);


ALTER TABLE `person`
    ADD COLUMN `enabled` boolean NOT NULL DEFAULT true AFTER `last_name`;

